"""posts table

Revision ID: 599909122d9b
Revises: dd7586098798
Create Date: 2019-11-12 09:31:17.718109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599909122d9b'
down_revision = 'dd7586098798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('wsuID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'wsuID')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'name')
    op.drop_column('user', 'lastname')
    # ### end Alembic commands ###
