"""empty message

Revision ID: 5ce15330b754
Revises: a30fbabd0c3b
Create Date: 2019-12-02 10:35:07.928635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce15330b754'
down_revision = 'a30fbabd0c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wsuID', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(length=140), nullable=True),
    sa.Column('instructor', sa.String(length=140), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('datetaken', sa.String(length=140), nullable=True),
    sa.Column('dateTA', sa.String(length=140), nullable=True),
    sa.Column('tabefore', sa.String(length=140), nullable=True),
    sa.Column('accepted', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apps')
    # ### end Alembic commands ###
