"""users table

Revision ID: c8ae795c96d5
Revises: d43e8ff99dc3
Create Date: 2019-11-11 18:28:13.837931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ae795c96d5'
down_revision = 'd43e8ff99dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_type'), 'user', ['type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_type'), table_name='user')
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
