"""posts table

Revision ID: dd7586098798
Revises: c8ae795c96d5
Create Date: 2019-11-12 08:29:57.145767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7586098798'
down_revision = 'c8ae795c96d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_type', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_type', 'user', ['type'], unique=1)
    # ### end Alembic commands ###
