"""empty message

Revision ID: e30c3673cf9d
Revises: 6027f4637452
Create Date: 2019-11-30 14:09:18.283387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30c3673cf9d'
down_revision = '6027f4637452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('TAs', sa.String(length=200), nullable=True))
    op.add_column('courses', sa.Column('available', sa.String(length=140), nullable=True))
    op.add_column('courses', sa.Column('instructor', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'instructor')
    op.drop_column('courses', 'available')
    op.drop_column('courses', 'TAs')
    # ### end Alembic commands ###
