"""empty message

Revision ID: fcfd895a76ff
Revises: e30c3673cf9d
Create Date: 2019-11-30 14:11:06.861478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcfd895a76ff'
down_revision = 'e30c3673cf9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('assigned', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'assigned')
    # ### end Alembic commands ###
